import type { Metadata } from "next";
import { PictureResponse, StoreResponse, PictureTypeResponse } from "@/app/_definitions/store";
import EditForm from "@/app/_component/master/picture/editForm";
import { Recoil } from "@/lib/recoilProvider";
import { Chakra } from "@/lib/chakraProvider";
import { FormProvider } from "react-hook-form";
import PictureFormProvider from "@/lib/pictureFormProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // 店舗リスト取得
  const stores:StoreResponse = await fetch(`${process.env.DEPLOY_PRIME_URL}/api/master/store`, {
		method: "GET",
		cache: "no-store"
	}).then(response => {
		return response.json();
	})

  // 画像種別リスト取得
  const picturesTypes:PictureTypeResponse = await fetch(`${process.env.DEPLOY_PRIME_URL}/api/master/picture-type?fgDelete=false`, {
		method: "GET",
		cache: "no-store"
	}).then(response => {
		return response.json();
	})


  return (
    <div className="flex flex-col w-full items-center">
      <Recoil>
        <PictureFormProvider>
          <EditForm fetchStores={stores.data} fetchPictureTypes={picturesTypes.data}></EditForm>
          <Chakra>{children}</Chakra>
        </PictureFormProvider>
      </Recoil>
    </div>
  );
}
